server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/wearther?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: seoho123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect


