server:
  port: 8080

logging:
  level:
    root: info
    com.min.fashion: debug

spring:
  thymeleaf:
    cache: false

  application:
    name: oauth2

  datasource:
    url: jdbc:mariadb://localhost:3306/wearther
    username: root
    password: seoho123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect



  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 427594503402-1u2205qktjca042164ffns2s4f9rfjd6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
          naver:
            client-name: naver
            client-id: FI7I4Rvr4NxIBb2FKX3t
            client-secret: pD1Unk1E6L
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: response
